### ISSUE TITLE
windows build recipe

### ISSUE THREAD

**Issue by glycerine** [gijit/gi#18]
todo: figure out how to get `gijit` to build on windows

Update NB: there are binaries available, at least since v1.0.9, here https://github.com/gijit/gi/releases  so if you want to try `gijit` on windows, you don't need to compile it. 

Update: Also binaries for Windows at v1.3.2: https://github.com/gijit/gi/releases/tag/v1.3.2

**Comment by glycerine** [comment]
I built `gi` on windows, successfully.

There's a windows branch currently with the changes; it will get merged.

Notes:

install mingw64, which is a port of the gcc compiler to windows.

https://sourceforge.net/projects/mingwbuilds/files/host-windows/releases/4.8.1/64-bit/threads-posix/seh/x64-4.8.1-release-posix-seh-rev5.7z/download

to extract mingw64 binary above, you'll need an 7z extractor, which is here
http://www.7-zip.org/

command to extsract the mingw64  .7z archive:

"\Program Files\7-Zip\7z.exe"  x   .\x64-4.8.1-release-posix-seh-rev5.7z

I installed gcc as 

C:\mingw64\bin\gcc.exe

then added

C:\mingw64\bin to my %PATH%  (system, advanced settings, environment vars)

then re-open the command prompt window.

also gnu make installed from 
https://phoenixnap.dl.sourceforge.net/project/gnuwin32/make/3.81/make-3.81.exe 

to 
C:\Program Files (x86)\GnuWin32\bin\make.exe

and add  C:\Program Files (x86)\GnuWin32\bin to %PATH%

I had to manually cd over to %GOPATH%\src\github.com\gijit\gi\vendor\LuaJIT\LuaJIT\src and run make; make libluajit.a  because gnu make was stumbling on windows paths contains spaces and parenthesis.

**Comment by glycerine** [comment]
Be sure to install gnuwin32/make in path that does not have spaces or parenthesis in it. So the default is bad.  "C:\Program Files (x86)\GnuWin32\bin\make.exe" is bad. Instead use "C:\GnuWin32\bin\make.exe" or similar.

https://github.com/iamantony/qtcsv/issues/19

**Comment by glycerine** [comment]
Since this is solved, closing issue.

**Comment by jordan4ibanez** [comment]
So when the windows build gets to this part `
C:\Users\jordan\Desktop\gi\vendor\github.com\LuaJIT\LuaJIT\src>make gijit_luajit
make: *** No rule to make target `gijit_luajit'.  Stop.
` it gives up, but if I cd to it, I can manually run make and it works

**Comment by glycerine** [comment]
Yeah, I see that too. I had hacked the makefile to produce a differently named luajit, namely gijit_luajit, to keep it separate from any other luajit, as gijit_luajit has some additional patches, and it seemed nice to keep them separate. So I can see from reading the Makefile that on Windows the LuaJIT/src/Makefile line 514 is overridden by line 536. It doesn't really matter since the .a is the only thing we're really after to link against.

**Comment by glycerine** [comment]
@jordan4ibanez  just by-the-by, gi isn't something I'm putting effort into. If you want a pretty functional go interpreter, https://github.com/cosmos72/gomacro is much more complete. Its only drawback I would say is the MPL license.
