### ISSUE TITLE
goroutines and channels

### ISSUE THREAD

**Issue by glycerine** [gijit/gi#2]
thoughts: (from 10)

Also there is this https://github.com/majek/lua-channels 
>Go style channels in pure Lua
>This code is derived from libtask library by Russ Cox, mainly from channel.c. Semantically channels as implemented here are quite similar to channels from the Go language.
  
discussion https://news.ycombinator.com/item?id=6329556

Ooooohh hold up. Steve Donovan's LuaR project claims to be able to both import Go libs into Lua, and to be able to send on channels.

https://github.com/stevedonovan/luar

He claims to have Lua object <-> Go struct transforms in place both directions. So if gi generates Lua objects directly that match their intended native Go struct, then we would have automatic access to all of the Go native standard library and scheduler. Which would be a big win.

**Comment by glycerine** [comment]
plan to use Luar's funtionality, and reflect for anything else.

**Comment by glycerine** [comment]
While native Go calls are working, its looking nicer and nicer to have the option of being independent of the go runtime, for sandboxing purposes in particular.

@elliott5 could you point me to where in https://github.com/tardisgo/tardisgo the goroutine/channel operations are turned into coroutine actions?  I'd like to study how you did that.

**Comment by elliott5** [comment]
The direct answer is ...

The goroutine scheduler is written in Haxe, it begins at https://github.com/tardisgo/tardisgo/blob/master/haxe/haxeRuntime.go#L2756

`runAll()` is where the goroutines are scheduled. 

Each goroutine is an entry in the Haxe array `grStacks` in the `Scheduler` class. Each entry in that array is another Haxe array on which `StackFrame`s are pushed & popped.

A `StackFrame` is what Go would call an interface, every function/method has its own StackFrame type, individually generated by TARDISgo. However they all share `StackFrameBasis` which can be found at https://github.com/tardisgo/tardisgo/blob/master/haxe/haxeRuntime.go#L2505

All Go functions/methods transpie to Haxe code which is a huge case statement, with `StackFrameBasis._Next` showing the next block of code to execute (a direct crib of the way SSA works).

That's probably enough to get you started.

The indirect answer is that Lua already has coroutines, so you'd probably find it simpler to use them.

Alternatively, the SSA interpreter used to just create a new Go goroutine when running an SSA goroutine!

What you must be clear about though is what typing `go myfunc()` at the REPL means ... do goroutines continue running when that command completes or do they all stop. Either way you'll need a way to stop goroutines in mid-flight.

I hope that helps, best of luck!

**Comment by glycerine** [comment]
Awesome! Thank you Elliott!

**Comment by glycerine** [comment]
paper discussing deterministic threading approaches:

http://groups.csail.mit.edu/commit/papers/09/asplos073-olszewski.pdf

**Comment by glycerine** [comment]
The simple path is to reuse the runtime scheduler. This allows interacting with native libraries, which is important for performance. 

v1.0.15 has gijit code (interpreted Go code, running in LuaJIT) able to instantiate native channels and exchange values between LuaJIT and compiled Go code.

The remaining part is having LuaJIT Lua code start a function in a goroutine. LuaJIT is re-entrant, but not threadsafe. Therefore in order to have more than one goroutine within LuaJIT that shares memory, we have a problem to solve.  Options

[1] We could make a new Lua state vm for each goroutine. Still cannot immediately share a pointer to the same struct/table though. So not sure this solves the issue.

[2] The GopherJS approach is to unwind stacks and re-use the same single underlying thread/goroutine to multiplex all other interpreted goroutines on top of. This keeps all pointers within LuaJIT sharable between interpreted goroutines. On its face, it doesn't appear allow those pointers to be shared with binary/compiled Go code.

CGO will also prohibit us from storing Go pointers in LuaJIT C-land code. 

So we will need to allocate the memory behind such pointers off-heap with respect to the binary Go garbage collector?  Hmm... still puzzling this one out.

**Comment by glycerine** [comment]
> What you must be clear about though is what typing go myfunc() at the REPL means ... do goroutines continue running when that command completes or do they all stop. Either way you'll need a way to stop goroutines in mid-flight.

@elliott5 If I go with the native Go runtime scheduler, which I'm inclined to start with as it seems to be the simplest choice, then I don't have a way to stop goroutines in mid-flight.  Although I'm probably missing something obvious, in your view, what begets the need to halt all goroutines in mid-flight?

Under the native runtime, background goroutines keep running in the background, even while the user may be typing a fresh command at the REPL. Typing `go myfunc()` at the REPL wouldn't change the inflight status of any other goroutine. It would launch the new goroutine and come back to the REPL prompt for the next bit of input.

I've got an experiment underway, so I'll probably discover any wrinkles soon enough :-)  But does that make sense?

**Comment by glycerine** [comment]
With the "every goroutine has its own house", I've discovered, the problem is that the functions that goroutines run are closures and typically use that fact to grab shared channels from their up-scopes.

So I'm thinking use the github.com/majek/lua-channels/ approach of built-in coroutines, but have them talk through actual go channels so that they don't have to care whether it is native Go on the other end or not (and it *can* be native Go library code).

**Comment by elliott5** [comment]
You are quite right, you can't stop a native Go goroutine mid-flight - my inaccurate language.

Pre-emption with co-routines relies on generating the pre-emption points into the transpiled code - on calls and/or inside loops - there are no right ways to do it and it is always an overhead. The alternative approach of pre-emption by timer interruption was too ambitious to me ;) 

Fortunately, I don't think you need pre-emption. 

From my own brief investigations I know that typing the following at the REPL prompt: 
```
import "some/native/go/library"
go library.Foo()
``` 
...is going to run in the background until the REPL is closed. 

That truth is important, because it means typing the following at the REPL prompt:
```
go func(){ for { fmt.Println("forever"); time.Sleep(1*time.Second); } }()
```
...must also run until the REPL stops for consistency.

For simplicity, you should avoid having two parallel goroutine/channel implementations running side-by-side (go-native/go-lua).

If each REPL-goroutine runs to completion inside its own LuaJIT runtime built on the (possible) closure that created it (as you describe), **but inside its own native go goroutine**, then all goroutines would be native goroutines - which would be easier to reason about and allow the use of go's own scheduler/channel infrastructure.

**Comment by glycerine** [comment]
I decided to start small, and just get the all-Lua/only-Lua version working first, before considering how to integrate with the native Go channels. Native channels work, sans goroutines, but I put that all on the back burner and just implemented straight up Lua-only coroutines. 

And they work pretty well. Functions using goroutines and channels code seem to run fine.  The tests are 900-905 in chan_test.go.  https://github.com/gijit/gi/blob/master/pkg/compiler/chan_test.go#L146 I'll probably build them out more, once I figure out the interaction at the repl.  The machinery for timeouts and default is in place, but I still need to test that. This was held up a little by the `time` package issues (https://github.com/gijit/gi/issues/21 ) that need addressing before its reasonable to test timeouts.

The interaction at the repl is still somewhat awkward; it's not kicking the background scheduler properly. Also Lua can't yield across a CGO boundary, and apparently I try to do that.

nice:
~~~
gi> ch := make(chan int)

elapsed: '50.158µs'
gi> go func() { a := <- ch; println("background goroutine got ", a); }()
top of scheduler
top of select, alt_array is size    1

elapsed: '81.883µs'
gi> ch <- 3
top of select, alt_array is size    1
top of scheduler
background goroutine got    3LL

elapsed: '54.63µs'
gi>
~~~

not so nice:
~~~
gi> ch := make(chan int)

elapsed: '23.745µs'
gi> func f() { for i:=7;i<12;i++ { println("before sending i=", i); ch <- i; println("after sending i", i); }}

elapsed: '32.718µs'
gi> go f()
top of scheduler
before sending i=	7LL
top of select, alt_array is size 	1

elapsed: '130.643µs'
gi> println("received: ", <-ch)
top of select, alt_array is size 	1
received: 	7LL                     <<<<<<<<<<< great! first one works

elapsed: '48.635µs'
gi> println("received: ", <-ch)
top of select, alt_array is size 	1
error from Lua vm.Call(0,0): '...s/jaten/go/src/github.com/gijit/gi/pkg/compiler/chan.lua:499: attempt to yield across C-call boundary'. supplied lua with: '_r = __recv(ch);         
	print("received: ", _r[1])'
lua stack:

========== begin DumpLuaStack: top = 1
DumpLuaStack: i=1, t= 4
 String : 	...s/jaten/go/src/github.com/gijit/gi/pkg/compiler/chan.lua:499: attempt to yield across C-call boundary
========= end of DumpLuaStack

gi>                 ^^^^^^^^^^^^^^^^<<<<<<<<<< arg, 2nd one crashes
~~~

Anyway, great progress has been made. I really appreciate the sounding board and encouragement here.

**Comment by glycerine** [comment]
This is just keeping my notes and journaling my observations -- comments welcome but optional.

The main wrinkle/challenge in the design seems to be this: the main Lua coroutine cannot yield.

If the main coroutine (the principle starting thread) tries to yield, we will get this error:

~~~
 $ luajit
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> coroutine.yield()
stdin:1: attempt to yield across C-call boundary
stack traceback:
    [C]: in function 'yield'
    stdin:1: in main chunk
    [C]: at 0x0100001690
>
~~~
PUC Lua is a little clearer about what is happening:
~~~
jaten@Jasons-MacBook-Pro ~/go/src/github.com/gijit/gi/pkg/compiler (master) $ lua
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
> coroutine.yield()
coroutine.yield()
attempt to yield from outside a coroutine <<<<<<<<<<<
stack traceback:
    [C]: in function 'coroutine.yield'
    stdin:1: in main chunk
    [C]: in ?
>
~~~
So while typically a send or receive might yield to the scheduler in order to block, awaiting the corresponding receive or send, the main coroutine is not allowed to do that.  It can resume other coroutines, but cannot yield itself.

So can the REPL run on a non-main coroutine? 

We've called from Go into Lua, where we start a coroutine, then we need to get the next chunk of input from the REPL to load and evaluate.  We can have the first line/string/chunk passed in as an argument, but how to get the 2nd line?  I guess we yield and wait to be resumed with it. 

So the REPL would be doing coroutine.resume() with each new line/chunk of code.

Ok. I think this will work. Giving it a try...

**Comment by glycerine** [comment]
Yep. That works. The code looks like this.
~~~
-- The main eval loop for the gijit REPL never returns.
-- It only compiles and runs 'code', then yeilds nil
-- or an error string.
--
-- Resume it with new code to run, ad inifinitum.
--
__gijitMainEvalLoop = function(code)

   local chunk, err
   while true do
     -- compile chunk to bytecode
     chunk, err = loadstring(code);
     if err ~= nil then
        err = "load error: "..tostring(err)
     else
        -- run the compiled bytecode
        ok, err = pcall(function() chunk() end)
        if not ok then
           err = "run error: "..tostring(err)
        end
     end;
   print("main loop: yielding err="..tostring(err))
   code = coroutine.yield(err)
   print("main loop: yield returned with new code: "..code)

   end -- while true
end

__gijitMainCoro = coroutine.create(__gijitMainEvalLoop)

__eval = function(code)
   print("__eval called with code: '"..code.."'")

   ok, err = coroutine.resume(__gijitMainCoro, code)
   if not ok then
      return ok, err
   end
   return true, "ok"
end
~~~

It seems to break my defer implementation as well as the native imports from Luar, but I think (hope, fingers crossed) those can be patched up to work.

**Comment by glycerine** [comment]
Luar (native go imports) are pretty borked in the presence of coroutines. I think I can fix them eventually (cf. https://github.com/aarzilli/golua/issues/65 and https://github.com/stevedonovan/luar/issues/46), but it will take a bit of work. 

To divide and conquer, I'm going to continue to work on the go/coroutine implementation and get that sharpened up.  Defers work; they were just using fmt.Sprintf for convenience, so that was just another instance of luar imports messing things up.

I'll polish the coroutine/goroutine stuff until I'm sure its working. Even then, it seems like it would be more convenient to be able to on-the-fly compile any source package to Lua. As Elliott pointed out, importing other packages needs to be convenient, since we rarely use main alone. So no native import would be required, ideally.

For performance, I'll want native imports, but for convenience and getting started (as well as sandboxing), I'll give priority to the full Lua-only implementation of external packages. 

Since imports of source packages via Lua-compilation depend on having goroutines working anyway, so thats the first stop. But its mostly working now, so it shouldn't be long until I can get to the build system.

**Comment by glycerine** [comment]
I have the goroutine system working in v1.2.2, the latest release. Although one cannot yet block at the REPL on a select that blocks forever or for a timeout (timeouts in general have the plumbing implemented but not the porcelain), one can send and receive on unbuffered channels.

https://github.com/gijit/gi/blob/master/pkg/compiler/goro_test.go#L55

shows the kind of tests that now pass. Setting up, at the REPL, a background goroutine that sends and receives:
~~~
  accumRecv := []int{}
  a0 := 0
  c1 := make(chan int)
  c2 := make(chan int)
  nextSend := 2

go func() {
      for {
         select {
            case c1 <- nextSend:
               println("background goro sent ", nextSend)
               nextSend++
            case r := <- c2:
               accumRecv = append(accumRecv, r)
               a0 = accumRecv[0]
               println("background goro received ", r)
         }
      }
}()
~~~ 
then one can
~~~
j2 := <-c1;

c2 <- 33
~~~
and send and receive.

**Comment by glycerine** [comment]
v1.2.6 implements close() on channels. Besides timeouts, that was the last big piece.

The remaining open question in my mind is what to do about code like 
~~~
select{}
~~~
at the REPL.  Or a select with a `case <- time.After(10 * time.Second):` clause.

Currently each new statement is evaluated on a fresh coroutine, one that is resumed by the background scheduler coroutine. This is needed to handle blocking receives, such as `<-ch` where ch is an unbuffered channel.  Since the routine executing the <-ch receive might block for a while, it needs to be on its own coroutine that can be scheduled to run once a send on ch happens.

But that also means if we evaluate `select{}`, the scheduler just leaks a coroutine, leaving the blocked-forever stack sitting unused, and returns to the REPL for more input. In some ways that seems eminently sensible.  

I'm not actually sure under what circumstances one would want just a raw `select{}` on the REPL.  So maybe its not a big deal.

**Comment by glycerine** [comment]
https://github.com/gijit/gi/issues/35 outlines the remaining work. 

With the v1.4.x releases, binary imports now work, and work from any goroutine. So the goroutine design is workable, and 99% done. Timeouts are the last piece, and #35 is opened specifically for them. Closing this out as a victory/progress celebration!
