### ISSUE TITLE
Installing on macOS 10.13.3 High Sierra

### ISSUE THREAD

**Issue by carlca** [gijit/gi#33]
macOS 10.13.3 High Sierra
Golang 1.10
iTerm2
ZSH + Oh My ZHS

Hello, I followed the instructions exactly, but I may have run into difficulties on running `make install`
I received this error message:
```
git branch --set-upstream-to=origin/master
Branch master set up to track remote branch master from origin.
CGO_LDFLAGS_ALLOW='.*\.a$' go get -t -d -u ./pkg/... ./cmd/...
## LuaJIT compilation is now done manually, with windows.bat or posix.sh
##cd vendor/github.com/LuaJIT/LuaJIT/src && make libluajit.a
CGO_LDFLAGS_ALLOW='.*\.a$' cd cmd/gi && make install
rm -f /Users/carlca/Code/go/bin/gi
CGO_LDFLAGS_ALLOW='.*\.a$' go install -ldflags "-X main.LastGitCommitHash=6154d80a52f645b9902cceba7f7cfa6bdc0389d2 -X main.BuildTimeStamp=2018-03-03T00:44:29+0000 -X main.GitBranch=master -X main.NearestGitTag=v1.3.0  -X main.GoVersion=go_version_go1.10_darwin/amd64"
# github.com/gijit/gi/pkg/compiler/shadow/gonum.org/v1/gonum/floats
../../pkg/compiler/shadow/gonum.org/v1/gonum/floats/floats.genimp.go:41:19: undefined: floats.Nearest
../../pkg/compiler/shadow/gonum.org/v1/gonum/floats/floats.genimp.go:42:29: undefined: floats.NearestWithinSpan
make[1]: *** [install] Error 2
make: *** [install] Error 2
```
I then tried running `gi` and received the message:
`zsh: command not found: gi`

What am I doing wrong?

**Comment by glycerine** [comment]
hmm... I'm not sure. Thanks for writing in. I'll check this out.

**Comment by glycerine** [comment]
While I'm troubleshooting this, I posted a binary, pre-built for OSX. It uses an embedded prelude, so it *should* be standalone, no other installation required. Give it a try in the meantime.

https://github.com/gijit/gi/releases/download/v1.3.1/gi_osx

**Comment by carlca** [comment]
I had to `chmod 755` the binary but it appeared to work ok. Thanks!

**Comment by glycerine** [comment]
gonum did some recent updates, so the build issue was due to version skew--they did breaking changes (renaming functions) without changing their version number. Oh well. I vendored gonum at the release I build against, so that won't be an issue going forward from v1.3.2.

**Comment by carlca** [comment]
I tried installing 1.3.2 and everything worked. Thanks very much!

**Comment by glycerine** [comment]
> I tried installing 1.3.2 and everything worked. Thanks very much!

Great!  Thanks for the update.
