### ISSUE TITLE
range iteration over utf8 strings

### ISSUE THREAD

**Issue by glycerine** [gijit/gi#4]
I added a red test to start this off. From within the $GOPATH/src/github.com/gijit/gi/pkg/compiler directory, run go test -v -run 041 to run the test in utf8_test.go.

The raw material is in https://github.com/gijit/gi/tree/master/pkg/utf8, it just needs integrating.

**Comment by vbmade2000** [comment]
The raw material is available in [https://github.com/gijit/gi/tree/master/pkg/utf8](https://github.com/gijit/gi/tree/master/pkg/utf8).

**Comment by glycerine** [comment]
@vbmade2000 How's it going? Are you stuck any where?

**Comment by glycerine** [comment]
This was too difficult of a first issue. I've gone ahead and made it work in v0.7.2
