### ISSUE TITLE
allow expressions starting with number/string at top level?

### ISSUE THREAD

**Issue by cosmos72** [gijit/gi#43]
Currently, gi does not allow expressions that start with a number at top level:
```
gi> 1+2
oops: 'problem detected during Go static type checking: '1:1: expected declaration, found 'INT' 1'' on input '1+2'
```
same for expressions that start with a string:
```
gi> "a"+"b"
oops: 'problem detected during Go static type checking: '1:1: expected declaration, found 'STRING' "a"'' on input '"a"+"b"'
```
I think adding them would be useful.

Expressions starting with an identifier, as for example `c+1` below, are fine:
```
gi> const c = 1<<63
elapsed: '21.79µs'
gi> c + 1
9223372036854775809ULL
elapsed: '282.715µs'
```

**Comment by glycerine** [comment]
This is working as intended. This required some careful consideration and balance of concerns int he design.  The advantage of the approach taken is that we continue to detect critical syntax errors in full  Go code. It was discussed in the README log here: https://github.com/gijit/gi#2018-jan-31-update  With this approach we catch typos as early as possible; at compile time. This is one of Go's biggest strengths that we do not wish to dilute.

To do math at the `gi` REPL, the simple expediency is to prefix your expressions with an `=`, as in Lua.  Also there is `==` which will enter "calculator mode"  which persists until given `:`'.

Example:

~~~
gi> 1+2                                                                                          
1+2                                                                                              
oops: 'problem detected during Go static type checking: '1:1: expected declaration, found 'INT' \
1'' on input '1+2'                                                                               
gi> = 1 + 2                                                                                      
= 1 + 2                                                                                          
3LL                                                                                              
                                                                                                 
elapsed: '156.5µs'                                                                               
gi> ==                                                                                           
==                                                                                               
Calculator mode.                                                                                 
calc mode> 1 + 2                                                                                 
1 + 2                                                                                            
3LL                                                                                              
                                                                                                 
elapsed: '111.236µs'                                                                             
calc mode> :                                                                                     
:                                                                                                
Go language mode.                                                                                
gi> 
~~~

**Comment by glycerine** [comment]
I'll leave this open in case anyone else has the same question.

**Comment by cosmos72** [comment]
Thanks for the clarification on the syntax `= 1 + 2`, I missed it.

I understand the reasoning, but it raises another question:  
why expressions starting with an identifier, as the `c + 1` in my original question, are instead allowed?
Syntactically, `1 + 2` and `c + 1` are identical: both are *go/ast.BinaryExpr -  compiled Go would reject both at top level, since it only accepts declaration, not statements or expression

**Comment by glycerine** [comment]
A reasonable point. I'm trying to keep the changes to the `gc` type checking machinery as minimal as possible, so that all those years of effort at getting it right aren't wasted and have to be redone. I did have to relax expressions a little more later to accept receives on a channel at the repl. I speculate that  perhaps `c + 1` working may be a side effect of that.

**Comment by glycerine** [comment]
v2.0.0 includes adjustments to the parser to allow expressions (such as `1+2`) at the top level.
